name: dbsm-geoservice
services:

  ####### POSTGIS #######
  postgres:
    container_name: ${PG_CONTAINER}
    build:
      context: .
      dockerfile: Dockerfile.postgis
    restart: unless-stopped
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./initdb/01_postgis.sql:/docker-entrypoint-initdb.d/01_postgis.sql
      - ./initdb/02_postgrest.sql:/docker-entrypoint-initdb.d/02_postgrest.sql
      - ./initdb/03_api_functions.sql:/docker-entrypoint-initdb.d/03_api_functions.sql
    networks:
      - dbsm-geoservice-net

  ####### PGADMIN #######
  pgadmin:
    container_name: dbsm_pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - dbsm-geoservice-net

  ####### POSTGREST #######
  postgrest:
    container_name: dbsm_postgrest
    image: postgrest/postgrest:${POSTGREST_VERSION}
    restart: unless-stopped
    ports:
      - "${POSTGREST_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:${PGRST_DB_AUTHENTICATOR_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_OPENAPI_MODE: ${PGRST_OPENAPI_MODE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbsm-geoservice-net

  swagger:
    container_name: dbsm_swagger
    image: swaggerapi/swagger-ui:${SWAGGER_VERSION}
    ports:
      - "${SWAGGER_PORT}:8080"
    expose:
      - "${SWAGGER_PORT}"
    environment:
      API_URL: http://localhost:${POSTGREST_PORT}/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbsm-geoservice-net

  ####### GEOSERVER #######
  geoserver:
    container_name: dbsm_geoserver
    image: kartoza/geoserver:${GEOSERVER_VERSION}
    restart: on-failure
    ports:
      - "${GEOSERVER_PORT}:8080"
    environment:
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\\n' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/geoserver/rest/about/version.xml" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./initdb/geoserver.xml:/opt/geoserver/data_dir/security/geoserver.xml
    networks:
      - dbsm-geoservice-net

networks:
  dbsm-geoservice-net:
    driver: bridge

volumes:
  postgres_data: {}
  pgadmin_data: {}
