version: '3'

dotenv: ['.env']

tasks:
  up:
    desc: "Start all services"
    cmds:
      - docker compose up --build -d
    silent: true
  down:
    desc: "Stop all services"
    cmds:
      - docker compose down
    silent: true
  stop:
    desc: "Stop all services"
    cmds:
      - docker compose stop
    silent: true
  start:
    desc: "Start all services"
    cmds:
      - docker compose start
    silent: true
  restart:
    desc: "Restart all services"
    cmds:
      - docker compose restart
    silent: true
  logs:
    desc: "Show logs for all services"
    cmds:
      - docker compose logs -f
    silent: true
  ps:
    desc: "Show status of all services"
    cmds:
      - docker compose ps
    silent: true
  import:
    desc: "📦 Import GPKG data into PostGIS | 🧰 Usage: task import -- CITY=malta -- VERSION=v1| 🌍 CITY options: austria, belgium, bulgaria, croatia, cyprus, czechia, denmark, estonia, finland, france, germany, greece, hungary, ireland, italy, latvia, lithuania, luxembourg, malta, netherlands, poland, portugal, romania, slovakia, slovenia, spain, sweden | Version options: v1, v2"

    cmds:
      - ./import_data.sh {{.CITY}} {{.VERSION}}
    vars:
      CITY: '{{.CITY | default "malta"}}'
      VERSION: '{{.VERSION | default "v1"}}'