version: '3'

dotenv: ['.env']

vars:
  CONTAINER_NAME: qgis-desktop
  QGIS_IMAGE: qgis/qgis:latest
  DATA_PATH: "{{.ROOT_DIR}}/qgis-desktop-data"

tasks:
  up:
    desc: "Start all services"
    cmds:
      - docker compose up --build -d
    silent: true
  down:
    desc: "Stop all services"
    cmds:
      - docker compose down
    silent: true
  stop:
    desc: "Stop all services"
    cmds:
      - docker compose stop
    silent: true
  start:
    desc: "Start all services"
    cmds:
      - docker compose start
    silent: true
  restart:
    desc: "Restart all services"
    cmds:
      - docker compose restart
    silent: true
  logs:
    desc: "Show logs for all services"
    cmds:
      - docker compose logs -f
    silent: true
  ps:
    desc: "Show status of all services"
    cmds:
      - docker compose ps
    silent: true
  import:
    desc: "📦 Import GPKG data into PostGIS | 🧰 Usage: task import -- CITY=malta -- VERSION=v1| 🌍 CITY options: austria, belgium, bulgaria, croatia, cyprus, czechia, denmark, estonia, finland, france, germany, greece, hungary, ireland, italy, latvia, lithuania, luxembourg, malta, netherlands, poland, portugal, romania, slovakia, slovenia, spain, sweden | Version options: v1, v2"

    cmds:
      - ./import_data.sh {{.CITY}} {{.VERSION}}
    vars:
      CITY: '{{.CITY | default "malta"}}'
      VERSION: '{{.VERSION | default "v1"}}'

  qgis:
    desc: "Lanza QGIS Desktop como contenedor gráfico independiente"
    deps: [qgis:ensure-xhost]
    cmds:
      - mkdir -p {{.DATA_PATH}}
      - docker run -d \
          --name {{.CONTAINER_NAME}} \
          --network host \
          -e DISPLAY={{.DISPLAY | default ":0"}} \
          -e QT_X11_NO_MITSHM=1 \
          -e LIBGL_ALWAYS_INDIRECT=1 \
          -e QGIS_RENDERER=software \
          -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
          -v {{.DATA_PATH}}:/home/qgis \
          {{.QGIS_IMAGE}} \
          qgis
    preconditions:
      - sh: "! docker ps -q -f name={{.CONTAINER_NAME}}"
        msg: "El contenedor {{.CONTAINER_NAME}} ya está en ejecución. Usa 'task qgis:restart' o 'task qgis:stop'."

  qgis:ensure-xhost:
    internal: true
    cmds:
      - xhost +local:docker

  qgis:stop:
    desc: "Detiene QGIS Desktop"
    cmds:
      - docker stop {{.CONTAINER_NAME}} || true
      - docker rm {{.CONTAINER_NAME}} || true
      - xhost -local:docker

  qgis:restart:
    desc: "Reinicia QGIS Desktop"
    cmds:
      - task qgis:stop
      - task qgis
  