#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
     -v auth_password="$PGRST_DB_AUTHENTICATOR_PASSWORD" \
     --username "$POSTGRES_USER" \
     --dbname "$POSTGRES_DB" <<'SQL'
CREATE ROLE IF NOT EXISTS web_anon NOLOGIN;
GRANT USAGE ON SCHEMA v1 TO web_anon;
GRANT USAGE ON SCHEMA v2 TO web_anon;
GRANT SELECT ON ALL TABLES IN SCHEMA v1 TO web_anon;
GRANT SELECT ON ALL TABLES IN SCHEMA v2 TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA v1 GRANT SELECT ON TABLES TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA v2 GRANT SELECT ON TABLES TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA v1 GRANT EXECUTE ON FUNCTIONS TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA v2 GRANT EXECUTE ON FUNCTIONS TO web_anon;

CREATE ROLE IF NOT EXISTS authenticator NOINHERIT LOGIN PASSWORD :'auth_password';
GRANT web_anon TO authenticator;

ALTER DEFAULT PRIVILEGES IN SCHEMA v1 REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLES FROM web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA v2 REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLES FROM web_anon;
SQL
